Repository puppetlabs/puppet-lint, pull requests merged in 2022-10, with the labels that each got.

#48 (GH-47) Expose additional indexes
  lib/puppet-lint/checkplugin.rb
Labels: enhancement

#49 (MAINT) Add CI and release workflows
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
Labels: maintenance

#51 (MAINT) Add community labeller
  .github/workflows/labeller.yml
Labels: maintenance

#53 (MAINT) Update CI trigger
  .github/workflows/ci.yml
Labels: maintenance

#55 (MAINT) Fix spacing issue
  lib/puppet-lint/plugins/check_whitespace/140chars.rb
  lib/puppet-lint/plugins/check_whitespace/80chars.rb
Labels: maintenance

#56 (MAINT) Rubocop updates for spec
  .rubocop.yml
  spec/puppet-lint/bin_spec.rb
  spec/puppet-lint/checks_spec.rb
  spec/puppet-lint/configuration_spec.rb
  spec/puppet-lint/data_spec.rb
  spec/puppet-lint/ignore_overrides_spec.rb
  spec/puppet-lint/lexer/string_slurper_spec.rb
  spec/puppet-lint/lexer/token_spec.rb
  spec/puppet-lint/lexer_spec.rb
  spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb
  spec/puppet-lint/plugins/check_classes/autoloader_layout_spec.rb
  spec/puppet-lint/plugins/check_classes/class_inherits_from_params_class_spec.rb
  spec/puppet-lint/plugins/check_classes/code_on_top_scope_spec.rb
  spec/puppet-lint/plugins/check_classes/inherits_across_namespaces_spec.rb
  spec/puppet-lint/plugins/check_classes/name_contains_uppercase_spec.rb
  spec/puppet-lint/plugins/check_classes/names_containing_dash_spec.rb
  spec/puppet-lint/plugins/check_classes/nested_classes_or_defines_spec.rb
  spec/puppet-lint/plugins/check_classes/parameter_order_spec.rb
  spec/puppet-lint/plugins/check_classes/right_to_left_relationship_spec.rb
  spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
  spec/puppet-lint/plugins/check_comments/slash_comments_spec.rb
  spec/puppet-lint/plugins/check_comments/star_comments_spec.rb
  spec/puppet-lint/plugins/check_conditionals/case_without_default_spec.rb
  spec/puppet-lint/plugins/check_conditionals/selector_inside_resource_spec.rb
  spec/puppet-lint/plugins/check_documentation/documentation_spec.rb
  spec/puppet-lint/plugins/check_nodes/unquoted_node_name_spec.rb
  spec/puppet-lint/plugins/check_resources/duplicate_params_spec.rb
  spec/puppet-lint/plugins/check_resources/ensure_first_param_spec.rb
  spec/puppet-lint/plugins/check_resources/ensure_not_symlink_target_spec.rb
  spec/puppet-lint/plugins/check_resources/file_mode_spec.rb
  spec/puppet-lint/plugins/check_resources/unquoted_file_mode_spec.rb
  spec/puppet-lint/plugins/check_resources/unquoted_resource_title_spec.rb
  spec/puppet-lint/plugins/check_strings/double_quoted_strings_spec.rb
  spec/puppet-lint/plugins/check_strings/only_variable_string_spec.rb
  spec/puppet-lint/plugins/check_strings/puppet_url_without_modules_spec.rb
  spec/puppet-lint/plugins/check_strings/quoted_booleans_spec.rb
  spec/puppet-lint/plugins/check_strings/single_quote_string_with_variables_spec.rb
  spec/puppet-lint/plugins/check_strings/variables_not_enclosed_spec.rb
  spec/puppet-lint/plugins/check_variables/variable_contains_dash_spec.rb
  spec/puppet-lint/plugins/check_variables/variable_is_lowercase_spec.rb
  spec/puppet-lint/plugins/check_whitespace/140chars_spec.rb
  spec/puppet-lint/plugins/check_whitespace/2sp_soft_tabs_spec.rb
  spec/puppet-lint/plugins/check_whitespace/80chars_spec.rb
  spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
  spec/puppet-lint/plugins/check_whitespace/hard_tabs_spec.rb
  spec/puppet-lint/plugins/check_whitespace/trailing_whitespace_spec.rb
  spec/puppet-lint_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#57 (GH-42) Fix Dockerfile
  Dockerfile
Labels: maintenance

#59 (MAINT) Update acceptance workflow
  .github/workflows/ci.yml
  Rakefile
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#62 (MAINT) Remove version constraint for rake
  Gemfile
Labels: maintenance

#63 (MAINT) Restore spec files in gems
  puppet-lint.gemspec
Labels: maintenance

#61 (MAINT) Bump gem version
  lib/puppet-lint/version.rb
Labels: maintenance

#66 Fix plugin regressions introduced in 3.0.0
  lib/puppet-lint/plugins.rb
  spec/spec_helper.rb
Labels: community

#67 (MAINT) Bump gem version to 3.0.1
  lib/puppet-lint/version.rb
Labels: maintenance
