Repository puppetlabs/puppet-lint, pull requests merged in 2023-02, with the labels that each got.

#80 pdksync - (CONT-211) Adding mend config
  .github/workflows/mend.yml
Labels: maintenance

#87 (CONT-339) Lower Ruby requirement
  puppet-lint.gemspec
Labels: enhancement

#88 (CONT-339) Update CI for ruby 2.5
  .github/workflows/ci.yml
Labels: maintenance

#85 (CONT-339) Add top scope facts check
  lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
  spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb
Labels: enhancement

#90 (MAINT) Add alexjfisher to plugin creds
  lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
Labels: maintenance

#86 Fix first token whitespace
  lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb
  spec/unit/puppet-lint/plugins/check_whitespace/trailing_whitespace_spec.rb
Labels: bug, community

#91 (CONT-670) Add legacy facts check
  lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
  spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb
Labels: enhancement

#92 (MAINT) Fix typo in check docstring
  lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
Labels: maintenance

#93 (CONT-666) Skip classref types
  lib/puppet-lint/data.rb
  spec/unit/puppet-lint/data_spec.rb
Labels: bug

#94 (CONT-674) Release Prep
  CHANGELOG.md
  lib/puppet-lint/version.rb
Labels: maintenance

#96 (CONT-675) Fix fact detection
  lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
  spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb
Labels: bug

#79 codeclimate (GitLab Code Quality compatible) output support
  README.md
  lib/puppet-lint.rb
  lib/puppet-lint/bin.rb
  lib/puppet-lint/configuration.rb
  lib/puppet-lint/optparser.rb
  lib/puppet-lint/report/codeclimate.rb
  lib/puppet-lint/tasks/puppet-lint.rb
  spec/fixtures/test/reports/code_climate.json
  spec/unit/puppet-lint/bin_spec.rb
  spec/unit/puppet-lint/configuration_spec.rb
Labels: community

#97 (MAINT) Release prep for v3.2.0
  CHANGELOG.md
  lib/puppet-lint/version.rb
Labels: maintenance
