Repository puppetlabs/puppet-lint, pull requests merged in 2023-10, with the labels that each got.

#156 (CAT-1434) Update README
  README.md
Labels: maintenance

#157 (CAT-1488) - Fix rubocop warnings
  rubocop_baseline.yml
Labels: maintenance

#160 (CAT-527) Update test coverage to fully cover unhandled exception error
  spec/unit/puppet-lint/checks_spec.rb
Labels: maintenance, hacktoberfest

#161 (CAT-1496) Removal of inappropriate terminology
  README.md
  lib/puppet-lint/lexer.rb
  lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
  spec/unit/puppet-lint/plugins/check_strings/double_quoted_strings_spec.rb
  spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb
Labels: maintenance

#162 (maint) - Fix undefined method have
  spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb
Labels: maintenance

#163 (CAT-1435) Address outdated code
  spec/unit/puppet-lint/plugins/check_classes/variable_scope_spec.rb
  spec/unit/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
  spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb
Labels: maintenance, hacktoberfest

#164 (CAT-1255) Release Gem with reference to the new name
  puppet-lint.gemspec
Labels: maintenance, hacktoberfest

#158 (CAT-1248) Update Published Name and Owner
  puppet-lint.gemspec
Labels: backwards-incompatible, hacktoberfest

#172 Use better yardoc tags
  lib/puppet-lint/data.rb
  lib/puppet-lint/plugins/check_whitespace/line_length.rb
Labels: community
